version: '3.8'

services:
  # Node.js application service
  microservice:
    build: .
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - AUTH_MS_URL=http://host.docker.internal:8000
      - PRODUCT_MS_URL=http://host.docker.internal:8002
      - DB_HOST=order-db
      - DB_PORT=5432
    ports:
      - "8001:8001"
    depends_on:
      - order-db

  # PostgreSQL database service
  order-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: order-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5428:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data

volumes:
  order_pgdata: