apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:latest
        command:
          - sh
          - -c
          - |
            until pg_isready -h auth-db-service -p 5432; do
              echo "waiting for database";
              sleep 2;
            done;
      containers:
      - name: auth-service
        image: vinkakniv/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: AUTH_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: AUTH_DATABASE_URL
        envFrom:
        - configMapRef:
            name: marketplace-config
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  selector:
    app: auth-service
