apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-config
data:
  AUTH_MS_URL: "http://auth-service.svc.cluster.local:8000"
  JWT_SECRET: "auth_ms_jwt_secret"
  AUTH_DB_HOST: "postgresql://postgres:postgres@auth-db-service.svc.cluster.local:5432/auth-db"
  AUTH_DATABASE_URL: "postgresql://postgres:postgres@auth-db-service:5432/auth-db"
  PRODUCT_DATABASE_URL: "postgresql://postgres:postgres@product-db-service:5432/product-db"
  WISHLIST_DATABASE_URL: "postgresql://postgres:postgres@wishlist-db-service:5432/wishlist-db"
  TENANT_DATABASE_URL: "postgresql://postgres:postgres@tenant-db-service:5432/tenant-db"
  ORDER_DATABASE_URL: "postgresql://postgres:postgres@order-db-service:5432/order-db"