apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
      - name: auth-service
        image: vinkakniv/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: AUTH_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: AUTH_DATABASE_URL
        envFrom:
        - configMapRef:
            name: marketplace-config
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "128m"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  selector:
    app: auth-service
