apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wishlist-service
  template:
    metadata:
      labels:
        app: wishlist-service
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:latest
        command: ['sh', '-c', 'until pg_isready -h wishlist-db-service -p 5432; do echo waiting for database; sleep 2; done;']
      containers:
      - name: wishlist-service
        image: wishlist-microservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8004
        envFrom:
        - configMapRef:
            name: marketplace-config
        env:
        - name: DB_HOST
          value: "wishlist-db-service"
        - name: DB_PORT
          value: "5432"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /health
            port: 8004
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
spec:
  type: NodePort
  ports:
  - port: 8004
    targetPort: 8004
    nodePort: 30004
  selector:
    app: wishlist-service 