version: '3.8'

services:
  marketplace-products:
    build: .
    ports:
      - "8002:8000"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=db-products
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=marketplace_products
    depends_on:
      - db-products

  db-products:
    image: postgres:latest
    environment:
      POSTGRES_DB: marketplace_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: