version: '3.8'

services:
  # Node.js application service
  microservice:
    build: .
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - AUTH_MS_URL=http://host.docker.internal:8000
      - DB_HOST=wishlist-db
      - DB_PORT=5432
    ports:
      - "8004:8004"
    depends_on:
      - wishlist-db

  # PostgreSQL database service
  wishlist-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: wishlist-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5429:5432"
    volumes:
      - wishlist_pgdata:/var/lib/postgresql/data

volumes:
  wishlist_pgdata: