version: '3.8'

services:
  # Node.js application service
  microservice:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=auth-db
      - DB_PORT=5432
    depends_on:
      - auth-db

  # PostgreSQL database service
  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

volumes:
  auth_pgdata: